- src/package/SuggestedCard.jsx
추천 카드의 상세 경로에 artistId 추가 navigate(`/detail${artistId}`);
프롭 네이밍 artistImg, artistName, artistId으로 통일
> #45: 추천 카드 props 및 라우팅 경로 수정

- src/features/agency/AgencySidebar.jsx
- src/index.css
- src/main.jsx
- src/package/modal/Modal.jsx
- src/package/modal/Modal.module.css
- src/testRoutes/testPages/thepott/ThePottTestPage.jsx
1. 모달 내용물을 클릭해도 꺼지지 않습니다
2. 모달 컴포넌트의 이름을 더 이해하기 쉽게 바꿨습니다
```
Modal
|- ModalBackdrop
|- ModalContent
```
> #43 모달 버그 수정

- src/main.jsx
- src/package/layout/_FullScreen.jsx
- src/package/layout/_FullScreen.module.css
- src/pages/SignupPage.jsx
1. api 보내기 전까지의 화면 및 로직 구현 완료
2. 테이블 명세서에 맞춰 입력값의 상한선 설정
3. 유효성 검사 제작
> #60 회원가입 페이지 만들기

- src/features/mypage/DeleteAccountModal.jsx
- src/features/mypage/PasswordChangeModal.jsx
- src/features/mypage/Sidebar.css
- src/features/mypage/Sidebar.jsx
- src/pages/MyPage.css
- src/pages/MyPage.jsx
흥주님이 말씀주신 3가지 부분 전부 수정 완료해서 다시 올렸습니다.
작업해야하는 브랜치를 잘못 바꿔서 작업해서 49-1 이라는 브랜치로 올립니다.
> #49 비밀번호 변경 모달 적용시키기

- src/features/signup/signupInputProps.js
- src/features/signup/useSignup.js
- src/index.css
- src/pages/SignupPage.jsx
**제목 템플릿**
1. 이메일 인증, 회원가입 api 연결
2. 인증한 메일과 같은 메일만 회원가입 시도 가능
> #89 이메일 인증 후 회원가입

- src/features/super-user/SuperuserApi.js
- src/pages/SuperUserPage.jsx
superuserpage에 있던 더미 데이터 제거, api 연동을 위한 SuperuserApi.js제작
말씀 주신대로 features/super-user/SuperuserApi.js 로 경로 해놓았습니다.
> #91 슈퍼 유저 페이지 api 연동 준비

- src/package/RoundBox.jsx
- src/package/RoundBox.module.css
- src/testRoutes/testPages/heehaa/HeeHaaTestPage.jsx
- src/testRoutes/testPages/heehaa/HeeHaaTestPage.module.css
> 외부 className으로 선언한 스타일이 반영되도록 수정
> 다크모드 시, 박스 쉐도우 보이도록 수정
> #101 라운드 박스 스타일 버그 수정

- src/features/login/loginComponents/SocialLoginButton.jsx
- src/features/login/loginComponents/SocialLoginButtonLabel.module.css
- src/features/login/loginServices/loginApi.js
- src/features/login/loginServices/useLogin.js
**제목 템플릿**
( http 문제를 해결하기 위해 배포판과 병합)
(진행중)
> #111 소셜 로그인 api 연결하기

- src/features/detail/DetailContent.jsx
- src/features/front/search/SearchContent.jsx
- src/features/layout/Navbar.jsx
- src/shared/store/dummyMijin.js
- src/testRoutes/_mijinTestRoutes.jsx
- src/testRoutes/testPages/mijin/MijinTestPage.jsx
1. 메인화면 (http://localhost:5173/)
1-1. "블랙.." 검색어 입력
1-1-1. 블랙핑크 (성공화면) 출력 
1-2. 검색창에 엔터
1-2-1. (실패화면) 로드 
- 검색 성공 시 검색어에 맞는 단일(또는 해당 조건에 맞는) 결과 화면에 표시
- 상태 관리 및 데이터 가공 로직 리팩토링
> #102 검색결과콘텐트,세부콘텐트__상태,데이터 로직 분리 리팩토링

- src/features/mypage/DeleteAccountModal.jsx
- src/features/mypage/UserApi.js
UserApi.js 파일 제작, UserApi.js와 DeleteAccountModel.jsx 연동, 코드 추가 및 오류 수정
window.alert()를 공통 모달 컴포넌트로 알람창이 뜨도록 수정.
> #105 마이페이지 회원탈퇴모달, 비밀번호 변경 모달 api추가 및 수정

- src/features/agency/AgencyModal.jsx
**제목 템플릿**
File 인풋을 사용해서 업로드 이미지를 확인할 수 있게 수정
> #128 소속사 페이지__아티스트 모달에서 이미지 보이게 개선하기

- src/package/modal/Modal.jsx
**제목 템플릿**
인라인 스타일이 적용되어있던 모달창을 라운드박스로 교체
> #134 공통 컴포넌트 모달__인라인 스타일 없애기 

- src/features/front/search/SearchContent.jsx
- src/features/mypage/FanPostWriteContent.jsx
- src/shared/FanPostGrid.jsx
- src/shared/store/dummy2Heehaa.json
- src/testRoutes/testPages/thepott/ThePottApiTestPage.jsx
> 팬포스트 생성 api 로직을 추가 - 스크린 샷은 에러가 나서 생략하였습니다.
> #163 팬포스트 api 연결

- src/features/front/search/SearchContent.jsx
**제목 템플릿**
(없음)
1. 미진님 최종 코드로 복사 붙여넣기
2. 프리티어로 포매팅
> #176 SearchContent 오류 해결

- src/features/front/search/SearchContent.jsx
- src/shared/ArtistCardNew/ArtistCardNew.jsx
- src/shared/FanPostSection.jsx
**제목 템플릿**
1. 검색 결과 출력 로직이 유실되어 일부 새로 작성
2. 검색 결과 보여주는 부분을 새로 만든 `ArtistCardNew` 와 기존의 `GridCardContainer`를 이용해 단순화
> #178 search content 오류 해결 2차

- src/features/front/search/SearchContent.jsx
- src/features/layout/Navbar.jsx
- src/features/super-user/SuperuserApi.js
- src/pages/SuperUserPage.jsx
- vite.config.js
슈퍼 유저 페이지 api 연동, 전체 유저 목록 불러오기,
유저 차단, 차단 해제 기능 구현
ps. > 사진과 같이 한번 차단했다가 차단해제를 하는 경우 유저 타입이 fan이 아닌 normal로 바뀌는 문제가 있습니다.
be 분들에게 수정해달라고 곧 요청해야 할 것 같습니다.
> #157 슈퍼 유저 페이지 api 연동

- src/features/layout/Navbar.jsx
**제목 템플릿**
null return 조건을 if (user) 에서 if (!user)로 수정
충돌 해결 과정에서 소실된 로그인 버튼 추가
> #198 프론트 페이지 유저 없을 때 유저 타입 확인하는 버그 해결

- src/features/agency/agencyComponents/AgencyCalendar.jsx
- src/features/agency/agencyComponents/AgencyCalendarAdditionalButtonMany.jsx
- src/index.css
- src/package/calendar/Calendar.jsx
- src/package/calendar/calendar.module.css
- src/package/calendar/useCalendar.js
- src/package/layout/_Hstack.jsx
- src/package/layout/_Hstack.module.css
- src/testRoutes/testPages/thepott/ThePottTestPage.jsx
**제목 템플릿**
1. 달력에서 추가 버튼을 받을 수 있는 props 추가
2. 달력에서 첫날 이전 날들, 마지막 날 이후 날들이 제대로 안 보이던 오류 해결
3. 버튼 헤더 갭 추가
> #185 달력에 버튼 추가할 수 있게 바꾸기

- src/features/detail/DetailContent.jsx
- src/features/front/recommend/RecommendContent.jsx
- src/features/front/total/TotalContent.jsx
- src/features/mypage/MyFanPost.jsx
- src/index.css
- src/package/gridContainer/GridContainer.jsx
- src/package/icons/PlusIcon.jsx
- src/shared/FanPostGrid.jsx
- src/shared/FanPostGrid.module.css
- src/shared/FanPostSection.jsx
- src/shared/GridCardContainer/GridCardContainer.jsx
- src/shared/SuggestedCard.jsx
- src/shared/store/store.js
- src/testRoutes/testPages/thepott/ThePottTestPage.jsx
**제목 템플릿**
(서버 다운으로 못 올립니다. 정상 작동까지 확인했습니다)
1. 모든 그리드는 `GridCardContainer`를 사용하게 수정
2. isMine, isBlurred 속성을 `FanPostGrid` 에 추가
3. 그리드 스타일 일원화
> #214 shared component__FanPostGrid 수정

- src/package/commonServices/fetchVariants.js
- src/testRoutes/testPages/thepott/ThePottApiTestPage.jsx
**제목 템플릿**
1. download 테스트 성공. 적용하면 됨
2. upload 테스트 성공. 백엔드 쪽 로직 수정 기다려야 함
> #207 일괄 업로드, 다운로드 테스트 버튼을 테스트 페이지에 제작하기

- src/features/agency/agencyComponents/AgencyArtistModal.jsx
- src/features/agency/agencyComponents/AgencyCalendar.jsx
- src/package/calendar/Calendar.jsx
- src/package/calendar/_DateCell.jsx
- src/package/calendar/_EventBox.jsx
- src/package/calendar/calendar.module.css
- src/package/layout/_Hstack.jsx
- src/shared/ArtistCalendar/ArtistCalendar.jsx
- src/shared/store/store.js
- src/testRoutes/testPages/thepott/ThePottApiTestPage.jsx
- src/testRoutes/testPages/thepott/ThePottTestPage.jsx
**제목 템플릿**
1. 전체 페이지, 세부 페이지에서 사용할 수 있는 ArtistCalendar 제작했습니다
2. 파라미터: `isMedium` <- 일정을 점으로만 표시하게 합니다
> #212 shared component__ArtistCalendar 제작하기

- src/features/agency/agencyComponents/AgencyArtistModal.jsx
- src/features/agency/agencyComponents/AgencyCalendar.jsx
- src/features/agency/agencyComponents/UploadModal.jsx
- src/shared/ArtistCalendar/AdditionalCalendarButtons.jsx
- src/shared/services/axiosInstance.js
**제목 템플릿**
1. 업로드 모달 제작
2. 업로드 템플릿 다운로드 기능 구현
3. 업로드 기능 구현
> #230 소속서 달력__업로드 버튼 기능 구현

- src/package/CustomInput.jsx
- src/package/CustomInput.module.css
- src/package/CustomInputLabeled.jsx
- src/package/CustomInputLabeled.module.css
**제목 템플릿**
1. 커스텀 인풋 코드 단순화
2. css 전역 변수를 이용한 스타일 개선
> #232 커스텀 인풋 스타일 개선

- src/features/front/search/SearchContent.jsx
- src/features/front/search/SearchContent.module.css
- src/features/front/search/SearchError.jsx
- src/features/front/search/SearchSkeleton.jsx
- src/features/front/search/SearchSubPage.jsx
- src/features/front/search/searchApi.jsx
- src/features/front/search/useEventsForSearch.js
- src/features/front/total/TotalContent.jsx
- src/features/front/useFront.js
- src/features/layout/Navbar.jsx
- src/index.css
- src/package/RoundBox.jsx
- src/package/RoundBox.module.css
- src/package/gridContainer/GridContainer.jsx
- src/package/layout/_Container.jsx
- src/package/layout/_Container.module.css
- src/pages/FrontPage.jsx
- src/shared/ArtistCardNew/ArtistCardNew.jsx
- src/shared/CustomImageBanner/CustomImageBanner.jsx
- src/shared/services/queryClient.js
- src/shared/services/useEvents.js
- src/shared/services/useIdol.js
- src/shared/services/useSubscriptions.js
- src/shared/store/store.js
**제목 템플릿**
1. api 연결
2. 페이지 레이아웃 재구성
3. `RoundBox`에 프로퍼티 추가
4. useIdol 후크 제작
> #241 검색 콘텐트 마저 제작

- src/features/detail/DetailContent.jsx
- src/shared/services/useSubscriptions.js
- src/shared/store/store.js
- src/testRoutes/testPages/thepott/ThePottTanstackTestPage.jsx
**제목 템플릿**
1. 커스텀 후크 안에서 endpoint를 query, mutate용으로 분리
2. 스토어 persist가 partial을 세션 스토리지가 아니라 로컬 스토리지에 저장하게 함
> #257 useSubscriptions 버그 수정

- src/features/login/loginComponents/SocialLoginButton.jsx
- src/pages/LoginPage.jsx
- src/shared/store/store.js
- src/shared/validations/zodSchema.js
**제목 템플릿**
1. 로딩, 에러 핸들링
2. 스토어에 아티스트 어레이 저장
> #261 로그인 로딩, 에러 핸들링

- src/pages/SuperUserPage.jsx
- src/pages/SuperUserPage.module.css
차단 해제 시 유저 상태가 fan이 아닌 normal로 바뀌는 문제 수정완료
> #246 차단 해제 시 유저 상태 변경 오류

- src/package/FileInput.jsx
> #164파일인풋 초기값 및 크기 조정 

- src/features/signup/useSignup.js
- src/package/modal/ConfirmationModal.jsx
- src/package/modal/ConfirmationModal.module.css
- src/package/modal/ErrorModal.jsx
- src/package/modal/Modal.jsx
- src/pages/LoginPage.jsx
- src/pages/SignupPage.jsx
- src/shared/services/useAuth.js
- src/shared/utils/stringUtils.js
- src/shared/validations/zodSchema.js
**제목 템플릿**
1. useMutate 이용해서 요청 로직 단순화
2. 공통 컴포넌트 ErrorModal 제작
3. 에러 모달 이용해 에러 핸들링
> #269 회원가입 useMutate 쓰도록 변경

- src/features/mypage/MyFanPostModal.jsx
> #271 좋아요 컴포넌트 삭제 

- src/pages/MyPage.jsx
가운데 구역까지 사용할 수 있도록 수정, 1줄만 사용하게 하는 코드 제거, 일정 이상 팬 포스트가 찼을 때 줄 바꿈
> #276 마이 페이지 카드 그리드 레이아웃 수정

- src/features/front/total/TotalContent.jsx
- src/features/front/total/TotalContent.module.css
- src/features/mypage/FanPostWriteContent.jsx
- src/shared/CustomImageIcon/CustomImageIcon.jsx
> #275전체 페이지와 피드 생성 버그 수정 

- src/features/mypage/MyFanPostModal.jsx
- src/features/mypage/MyFanPostModal.module.css
- src/package/CommentBox.jsx
- src/package/CommentBox.module.css
- src/package/CommentColumn.jsx
- src/package/CommentColumn.module.css
- src/package/modal/Modal.module.css
- src/shared/CommentInput.jsx
- src/shared/utils/dateUtils.js
**제목 템플릿**
1. 모달창에서 각 요소 잘 보이게 스타일, 레이아웃 개선
2. tanstack mutate으로 댓글 작성 -> 실시간 ui 반영
3. 코멘트 날짜를 지금부터의 시간 간격으로 표시
> #292 팬포스트 모달__코멘트 mutate

- src/features/agency/agencyComponents/AgencySidebar.jsx
**제목 템플릿**
close #303
1. 그룹 이름으로 묶음
2. 솔로는 최상단에 오게 함
3. 빈 그룹은 가운데 정렬로 스타일 구분
> #303 소속사 페이지__사이드바__버튼 그룹 만들기

- src/features/agency/agencyComponents/AgencySidebar.jsx
- src/features/agency/agencyComponents/AgencySidebar.module.css
**제목 템플릿**
1. 선택된 아티스트는 isOn으로 강조
> #305 소속사 페이지__사이드바__선택 아티스트 시각적으로 강조

- src/index.css
- src/testRoutes/testPages/thepott/ThePottTestPage.jsx
> #309 전역 css 변수 __ 빨강, 파랑, 노랑 수정

- src/package/CustomInput.jsx
- src/package/customImage/CustomImageContainer.jsx
- src/package/customImage/CustomImageContainer.module.css
- src/package/imageInput/ImageInput.jsx
- src/pages/MyPage.jsx
**제목 템플릿**
1. 이미지 변경하면 내 프로필 이미지 변경
2. 닉네임 변경하면 내 프로필 닉네임 변경
3. CustomInput에서 엔터 누르면 자동 blur 되게 변경
> #315 마이페이지__내 정보 수정 api 연결

- src/features/detail/DetailContent.jsx
- src/features/detail/DetailContent.module.css
- src/features/detail/useDetailContent.js
- src/shared/ArtistIconBar/ArtistIconBar.jsx
- src/shared/FanPostGrid.jsx
- src/shared/services/useSubscriptions.js
**제목 템플릿**
1. 레이아웃 수정
2. api 재연결
3. 비구독, 비로그인 상태에서 팬 포스트 클릭하면 모달 보여줌
> #319 세부 페이지__자잘한 버그들 해결

- src/features/detail/DetailContent.jsx
- src/features/front/total/TotalContent.jsx
- src/features/mypage/MyFanPost.jsx
- src/main.jsx
- src/package/calendar/_DateCell.jsx
- src/package/layout/_Container.module.css
- src/pages/MyPage.jsx
**제목 템플릿**
```jsx
const productRouteArray = [
{ path: "/", element: <FrontPage /> },
{ path: "/detail/:type/:id", element: <DetailPage /> },
{ path: "/mypage", element: <MyPage /> },
{ path: "/mypage/write", element: <FanPostWritePage /> },
{ path: "/agency", element: <AgencyPage /> },
{ path: "/signup", element: <SignupPage /> },
{ path: "/login", element: <LoginPage /> },
{ path: "/super-user", element: <SuperUserPage /> },
];
const suspenedRouteArray = productRouteArray.map((route) => ({
path: route.path,
element: <Suspense>{route.element}</Suspense>,
}));
```
1. laxy import -> suspense
2. 키 없이 매핑하던 것 수정
> #321 lazy import

- src/features/agency/agencyComponents/AgencySidebar.jsx
- src/features/front/recommend/RecommendContent.jsx
- src/features/front/recommend/RecommendContentSkeleton.jsx
- src/features/layout/Navbar.jsx
- src/features/layout/Navbar.module.css
- src/features/mypage/FanPostWritePage.jsx
- src/features/signup/useSignup.js
- src/package/CustomInput.jsx
- src/pages/AgencyPage.jsx
- src/pages/LoginPage.jsx
- src/pages/MyPage.jsx
- src/pages/SignupPage.jsx
- src/pages/SuperUserPage.jsx
- src/shared/services/useAuth.js
- src/shared/store/store.js
- src/shared/utils/useRedirectIfNot.js
**제목 템플릿**
1. 로그인, 회원가입 페이지에서는 로고만 보이게 수정
2. 권한 없는 페이지 방문하면 리다이렉트
> #323 로그인, 회원가입 관련 자잘한 버그 수정
